name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  unix_build: # job id, can be any string
    name: Unix Build
    # This job runs on Linux
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            triplet: x64-linux
            cc: g++
            dont_pack_tokens: 0
            no_exception: 0
            
          - os: ubuntu-22.04
            triplet: x32-linux
            cc: g++
            dont_pack_tokens: 0
            no_exception: 0
            
          - os: ubuntu-22.04
            triplet: x64-linux
            cc: g++
            dont_pack_tokens: 1
            no_exception: 0

          - os: ubuntu-22.04
            triplet: x32-linux
            cc: g++
            dont_pack_tokens: 1
            no_exception: 0

          - os: ubuntu-22.04
            triplet: x64-linux
            cc: g++
            dont_pack_tokens: 1
            no_exception: 1

          - os: ubuntu-22.04
            triplet: x32-linux
            cc: g++
            dont_pack_tokens: 1
            no_exception: 1
            
          - os: macos-latest
            triplet: x64-osx
            cc: clang++
            dont_pack_tokens: 0
            no_exception: 0
            
          - os: macos-latest
            triplet: x32-osx
            cc: clang++
            dont_pack_tokens: 0
            no_exception: 0
            
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build & Test
        shell: bash
        env:
          TRIPLET: ${{ matrix.triplet }}
          USE_CC: ${{ matrix.cc }}
          DONT_PACK_TOKENS: ${{ matrix.dont_pack_tokens }}
          NO_EXCEPTIONS: ${{ matrix.no_exception }}
        run: |
          echo "TRIPLET=$TRIPLET, USE_CC=$USE_CC, DONT_PACK_TOKENS=$DONT_PACK_TOKENS, NO_EXCEPTIONS=$NO_EXCEPTIONS"
          git status
          cd test
          case "$DONT_PACK_TOKENS$NO_EXCEPTIONS" in
            "00")
              echo "with exceptions enabled and with packed the tokens"
              CC=$USE_CC cmake . -DCMAKE_BUILD_TYPE=Release && make && ./flatjson
            ;;
            "01")
              echo "WITHOUT exceptions and with packed the tokens" && \
              CC=$USE_CC cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-fno-exceptions" && \
              ./flatjson
            ;;
            "10")
              echo "with exceptions and WITHOUT packing the tokens" && \
              CC=$USE_CC cmake . -DCMAKE_BUILD_TYPE=Release -D__FJ__DONT_PACK_TOKENS && \
              ./flatjson
            ;;
              echo "WITHOUT exceptions and WITHOUT packing the tokens" && \
              CC=$USE_CC cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-fno-exceptions" -D__FJ__DONT_PACK_TOKENS && \
              ./flatjson
            "11")
            ;;
          esac
