name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  unix_build: # job id, can be any string
    name: Unix Build
    # This job runs on Linux
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            triplet: x64-linux
            cc: g++

          - os: ubuntu-22.04
            triplet: x32-linux
            cc: g++

          - os: macos-latest
            triplet: x64-osx
            cc: clang++

          - os: macos-latest
            triplet: x32-osx
            cc: clang++

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build & Test
        shell: bash
        env:
          TRIPLET: ${{ matrix.triplet }}
          USE_CC: ${{ matrix.cc }}
        run: |
          echo "TRIPLET=$TRIPLET, USE_CC=$USE_CC"
          cd test
          CXX=$USE_CC cmake --no-warn-unused-cli . -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          ./flatjson-test

  vs2019_2022_build: # job id, can be any string
    name: Visual Studio Build
    strategy:
      matrix:
        include:
          - os: windows-latest
            generator: "Visual Studio 17 2022"
            platform: x64

          - os: windows-latest
            generator: "Visual Studio 17 2022"
            platform: x32

          - os: windows-2019
            generator: "Visual Studio 16 2019"
            platform: x64

          - os: windows-2019
            generator: "Visual Studio 16 2019"
            platform: x32

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build & Test
        shell: bash
        env:
          CMAKE_GENERATOR: ${{ matrix.generator }}
          PLATFORM: ${{ matrix.platform }}
        run: |
          echo "PLATFORM=$PLATFORM, CMAKE_GENERATOR=\"$CMAKE_GENERATOR\""
          cd test
          if [[ $PLATFORM == x32 ]]; then
            cmake --no-warn-unused-cli . -G "$CMAKE_GENERATOR" -A Win32 -DCMAKE_BUILD_TYPE=Release
          else
            cmake --no-warn-unused-cli . -G "$CMAKE_GENERATOR" -DCMAKE_BUILD_TYPE=Release
          fi
          cmake --build .
          Debug/flatjson-test.exe
